### ISSUE TITLE
0.2.5 Release Version Pinning Breaks Upstream Dependencies

### ISSUE THREAD

**Issue by jeremybeeman** [Invicton-Labs/terraform-null-assertion#5]
Hello. I was working with the terraform-external-shell-resource on version v0.3.3. I was using the module and then ran into a constraint issue in that module on that version stating that the state_keeper's usage of this assertion module required terraform version 1.9.0 or higher. We are on terraform 1.4.

State keeper assertion pinning: version       = "~> 0.2.1"

Would it be possible to make this 0.2.5 version not a patch level and instead a minor or major version bump to not break upstream dependencies? If not, is there another solution we could utilize? I'd be fine to move up to a higher terraform version, but the terraform-external-shell-resource and the terraform-null-state-keeper modules both will then not have correct version pinning requirements on older versions.

Thanks!

**Comment by rd-andres-zurita** [comment]
I run into the same issue, can we please do as @jeremybeeman suggested? would be a better way to handle the upgrade... thanks!

**Comment by KyleKotowick** [comment]
@jeremybeeman Could you clarify what you mean by the `terraform-external-shell-resource` and `terraform-null-state-keeper` modules not having correct version pinning requirements?

We generally define a patch release as one that:
1. Doesn't add additional required inputs
2. Doesn't change functionality
3. Doesn't break backwards compatibility
    - Dependency version bumps that don't break backwards compatibility are considered OK

Since Terraform [guarantees](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises) that all 1.X (minor version) releases will be backwards compatible, changing a minor version dependency for Terraform doesn't violate constraint 3.

Our preferred approach would be to make fixes to any of our other modules that break with this change.

**Comment by KyleKotowick** [comment]
Closing since there's been no response.
